### ISSUE TITLE
Compiling under mac os x 10.9

### ISSUE THREAD

**Issue by ghost** [stevengj/nlopt#10]
I had an issue compiling the matlab plugin for NLopt under mac os x 10.9. The error I was getting is:
"Undefined symbols for architecture x86_64:
 "___emutls_get_address", referenced from:
     _nlopt_srand in libnlopt.a(general.o)
     _nlopt_srand_time in libnlopt.a(general.o)
     _nlopt_srand_time_default in libnlopt.a(general.o)
     _nlopt_seconds in libnlopt.a(timer.o)
     _nlopt_init_genrand in libnlopt.a(mt19937ar.o)
     _nlopt_genrand_int32 in libnlopt.a(mt19937ar.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

   mex: link of ' "nlopt_optimize-mex.mexmaci64"' failed."

All that was necessary to resolve this was to add the following in timer.c (after line 34: #endif):
# ifdef **MACH**
# include <mach/clock.h>
# include <mach/mach.h>
# endif

**Comment by bdiazdeastarloa** [comment]
Hi I am having the same problem when trying to compile in MATLAB R2014a in OS X 10.10:
Error using mex
Undefined symbols for architecture x86_64:
  "___emutls_get_address", referenced from:
      _nlopt_srand in libnlopt.a(general.o)
      _nlopt_srand_time in libnlopt.a(general.o)
      _nlopt_srand_time_default in libnlopt.a(general.o)
      _nlopt_seconds in libnlopt.a(timer.o)
      _nlopt_init_genrand in libnlopt.a(mt19937ar.o)
      _nlopt_genrand_int32 in libnlopt.a(mt19937ar.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have indicated the mex path, but this persists. Where do I find the timer.c to try the edit suggested above?

Thanks a lot.
