### PR TITLE
fix conversion error in stop.c

### PR DESCRIPTION
**Pull request by jschueller**
hi,

I got this error introduced by 61fe516 when compiling git head with gcc:

```
make[2]: Entering directory '/home/schueller/projects/nlopt/build/util'
/bin/sh ../libtool  --tag=CC   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../util -I..  -I../../api   -g -O2 -Wall -W -Wcast-qual -Wpointer-arith -Wcast-align -Wno-long-long -pedantic -Wshadow -Wwrite-strings -Wredundant-decls -Wundef -Wconversion -MT stop.lo -MD -MP -MF .deps/stop.Tpo -c -o stop.lo ../../util/stop.c
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../util -I.. -I../../api -g -O2 -Wall -W -Wcast-qual -Wpointer-arith -Wcast-align -Wno-long-long -pedantic -Wshadow -Wwrite-strings -Wredundant-decls -Wundef -Wconversion -MT stop.lo -MD -MP -MF .deps/stop.Tpo -c ../../util/stop.c  -fPIC -DPIC -o .libs/stop.o
../../util/stop.c: In function ‘char* nlopt_vsprintf(char*, const char*, __va_list_tag*)’:
../../util/stop.c:151:20: error: invalid conversion from ‘void*’ to ‘char*’ [-fpermissive]
         p = realloc(p, len);
                    ^
Makefile:426: recipe for target 'stop.lo' failed
```

It should be the same as line 144: https://github.com/jschueller/nlopt/blob/d88458176f694c7c38e2f75c7e3da9e65db6812c/util/stop.c#L144

### CODE REVIEW

**Comment by stevengj** [comment]
Sure.  (The implicit cast is valid in C, but is not valid in C++.)
